from Agents.base_agent import BaseAgent

from Core.article_summary_parser import ArticleSummaryParser
from Core.comparison_matrix_builder import ComparisonMatrixBuilder
from Core.evidence_builder import EvidenceBuilder
from Core.event_logger import log
from Core.full_text_context_builder import FullTextContextBuilder


class Summarizer(BaseAgent):
    """
    Analyzes every selected scientific publication separately.

    The agent works in two modes:

    - FULL_TEXT_SECTIONS:
      metadata, abstract and selected full-text sections are analyzed;

    - ABSTRACT_ONLY:
      only metadata and the available abstract are analyzed.

    After extraction, a deterministic Comparison Matrix is created
    without an additional LLM call.
    """

    PROMPT_NAME = "summarizer"
    MODEL_NAME = "SUMMARIZER_MODEL"

    def execute(self, task):
        summaries = []

        source_scope_counts = {
            "FULL_TEXT_SECTIONS": 0,
            "ABSTRACT_ONLY": 0,
        }

        source_report = []

        for key in (
            "article_summaries",
            "comparison_matrix",
            "summary_source_report",
            "keywords",
            "methodologies",
            "findings",
            "limitations",
            "conclusions",
        ):
            task.memory.remove(key)

        papers = task.papers.get_all()

        log(
            "Summarizer",
            f"Получено статей для анализа: {len(papers)}",
        )

        for article_number, paper in enumerate(
            papers,
            start=1,
        ):
            source_package = FullTextContextBuilder.build(
                paper
            )

            source_scope = source_package[
                "source_scope"
            ]

            source_sections = source_package[
                "source_sections"
            ]

            source_text = source_package[
                "source_text"
            ]

            source_text_characters = source_package[
                "source_text_characters"
            ]

            full_text_url = source_package[
                "full_text_url"
            ]

            full_text_source = source_package[
                "full_text_source"
            ]

            source_scope_counts[source_scope] = (
                source_scope_counts.get(
                    source_scope,
                    0,
                )
                + 1
            )

            authors_text = self._authors_text(
                getattr(
                    paper,
                    "authors",
                    [],
                )
            )

            prompt = f"""
Analyze exactly one scientific publication.

This is ARTICLE {article_number} in the current research corpus.

SOURCE PROVENANCE

Source scope:
{source_scope}

Full-text sections supplied:
{", ".join(source_sections) if source_sections else "None"}

Source-text characters:
{source_text_characters}

The full-text URL and source below are provenance metadata only.
Do not derive scientific findings from the URL or source name.

Full-text source:
{full_text_source or "Not available"}

Full-text URL:
{full_text_url or "Not available"}

BIBLIOGRAPHIC METADATA

Title:
{paper.title}

Authors:
{authors_text}

Journal:
{paper.journal}

Year:
{paper.year}

DOI:
{paper.doi}

SUPPLIED SOURCE TEXT

{source_text}
"""

            log(
                "Summarizer",
                (
                    f"ARTICLE {article_number}: "
                    f"режим={source_scope}; "
                    f"разделы={source_sections}; "
                    f"символов={source_text_characters}"
                ),
            )

            answer = self.ask_llm(
                prompt
            )

            summary = ArticleSummaryParser.parse(
                answer,
                paper,
            )

            # Provenance is assigned deterministically.
            # It is not generated by the language model.
            summary.source_scope = source_scope

            summary.source_sections = list(
                source_sections
            )

            summary.source_text_characters = (
                source_text_characters
            )

            summary.full_text_url = full_text_url
            summary.full_text_source = full_text_source

            summaries.append(
                summary
            )

            source_report.append(
                {
                    "article_number": article_number,
                    "title": summary.title,
                    "source_scope": source_scope,
                    "source_sections": list(
                        source_sections
                    ),
                    "source_text_characters": (
                        source_text_characters
                    ),
                    "full_text_url": full_text_url,
                    "full_text_source": full_text_source,
                }
            )

            task.memory.add_article_summary(
                summary
            )

            for keyword in summary.keywords:
                task.memory.add_keyword(
                    keyword
                )

            task.memory.add_methodology(
                summary.methodology
            )

            task.memory.add_finding(
                summary.findings
            )

            task.memory.add_limitation(
                summary.limitations
            )

            task.memory.add_conclusion(
                summary.conclusion
            )

            task.memory.add_research_objective(
                summary.research_objective
            )

            task.memory.add_study_type(
                summary.study_type
            )

            task.memory.add_result(
                summary.results
            )

            task.memory.add_strength(
                summary.strengths
            )

            task.memory.add_weakness(
                summary.weaknesses
            )

            task.memory.add_practical_implication(
                summary.practical_implications
            )

            task.memory.add_future_research(
                summary.future_research
            )

            for fact in summary.verified_facts:
                task.memory.add_verified_fact(
                    fact
                )

            log(
                "Summarizer",
                (
                    f"ARTICLE {article_number} обработана: "
                    f"{summary.title}; "
                    f"источник={summary.source_scope}"
                ),
            )

        task.article_summaries = summaries

        task.memory.set(
            "summary_source_report",
            source_report,
        )

        task.comparison_matrix = (
            ComparisonMatrixBuilder.build(
                summaries
            )
        )

        task.memory.set(
            "comparison_matrix",
            task.comparison_matrix,
        )

        task.evidences = EvidenceBuilder.build(
            summaries
        )

        task.result = summaries

        evidence_levels = {}

        for row in task.comparison_matrix:
            level = row.get(
                "abstract_evidence_level",
                "Unknown",
            )

            evidence_levels[level] = (
                evidence_levels.get(
                    level,
                    0,
                )
                + 1
            )

        log(
            "Summarizer",
            f"Summaries создано: {len(summaries)}",
        )

        log(
            "Summarizer",
            (
                "Источники summaries: "
                f"FULL_TEXT_SECTIONS="
                f"{source_scope_counts['FULL_TEXT_SECTIONS']}; "
                f"ABSTRACT_ONLY="
                f"{source_scope_counts['ABSTRACT_ONLY']}"
            ),
        )

        log(
            "Summarizer",
            (
                "Comparison Matrix создана: "
                f"{len(task.comparison_matrix)} строк"
            ),
        )

        log(
            "Summarizer",
            (
                "Уровни пригодности доказательств: "
                f"{evidence_levels}"
            ),
        )

        return summaries

    @staticmethod
    def _authors_text(
        authors,
    ) -> str:
        """
        Convert the authors field into readable text.
        """

        if authors is None:
            return ""

        if isinstance(
            authors,
            str,
        ):
            return authors.strip()

        if isinstance(
            authors,
            (
                list,
                tuple,
                set,
            ),
        ):
            return ", ".join(
                str(author).strip()
                for author in authors
                if str(author).strip()
            )

        return str(
            authors
        ).strip()